version: '3.8'

services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      # Mount source files for live development
      - ./seawave-angular/src:/app/src
      - ./seawave-angular/angular.json:/app/angular.json
      - ./seawave-angular/tsconfig.json:/app/tsconfig.json
      - ./seawave-angular/tsconfig.app.json:/app/tsconfig.app.json
      # Exclude node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Keep the container running
    stdin_open: true
    tty: true 