# Development Dockerfile for Angular
FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY seawave-angular/package*.json ./
RUN npm install

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy the Angular project
COPY seawave-angular/ .

# Expose the port Angular uses
EXPOSE 4200

# Command to run Angular in development mode with host set to 0.0.0.0 to make it accessible from outside the container
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"] 