version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./seawave-angular/src:/app/src
      - ./seawave-angular/dist:/app/dist
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  node_modules: 