version: '3.8'

services:
  # Development service - run with: docker compose --profile dev up
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    ports:
      - "4200:4200"
    volumes:
      - ./seawave-angular/src:/app/src
      - ./seawave-angular/angular.json:/app/angular.json
      - ./seawave-angular/tsconfig.json:/app/tsconfig.json
      - ./seawave-angular/tsconfig.app.json:/app/tsconfig.app.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles: ["dev"]
    stdin_open: true
    tty: true

  # Regular development (built and served by nginx) - run with: docker compose up
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: development
    ports:
      - "80:80"
    volumes:
      - ./seawave-angular/src:/app/src
      - ./seawave-angular/dist:/app/dist
      - node_modules:/app/node_modules
    profiles: ["default"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Production service - run with: docker compose --profile prod up
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles: ["prod"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules: 